/**
 * platform/admin/types.ts — Config management types
 *
 * Types for the config management agent, tool handlers, two-person
 * approval workflow, change history, impact correlation, and validation.
 *
 * Maps to Migration 011 schema:
 *   - Enhanced platform_config (value_type, permission_tier, validation metadata)
 *   - platform_config_history (full change audit trail)
 *   - config_pending_approvals (two-person approval, built disabled)
 *
 * GenAI Principles:
 *   P2  — Agentic execution: config agent is bounded, multi-step, instrumented
 *   P3  — Total observability: every config change traced with trajectory
 *   P5  — Versioned artifacts: tool definitions typed and registerable
 *   P6  — Structured outputs: all agent results enforce schemas
 *   P10 — Human oversight: reconfirmation + optional two-person approval
 *   P12 — Economic transparency: agent cost tracked per trajectory
 *   P13 — Control plane: permission tiers enforce admin vs super_admin
 *   P15 — Agent identity: config agent has actorType/actorId/agentRole
 *   P17 — Cognition-commitment: evaluate internally, commit once (with confirm)
 *   P18 — Durable trajectories: full step history per conversation turn
 *
 * @module platform/admin
 */

import type { Step } from "@/platform/agents/types";

// ---------------------------------------------------------------------------
// Config value types — drives UI widget + validation (Migration 011)
// ---------------------------------------------------------------------------

/**
 * Value type for a config entry. Determines the UI input widget
 * and the validation rules applied on update.
 *
 *   string      — free-form text
 *   number      — numeric, respects min_value/max_value
 *   boolean     — true/false toggle
 *   string_enum — constrained to allowed_values list
 *   json_array  — JSON array (e.g., supported_languages)
 */
export type ConfigValueType =
  | "string"
  | "number"
  | "boolean"
  | "string_enum"
  | "json_array";

// ---------------------------------------------------------------------------
// Permission tiers — who can change what (Migration 011)
// ---------------------------------------------------------------------------

/**
 * Permission tier for a config entry.
 *
 *   standard — admin or super_admin can change (config_manage_standard)
 *   safety   — super_admin only (config_manage_safety). Covers moderation
 *              thresholds, strike limits, COPPA settings, system flags.
 */
export type PermissionTier = "standard" | "safety";

// ---------------------------------------------------------------------------
// Enhanced config entry — includes Migration 011 metadata
// ---------------------------------------------------------------------------

/**
 * Full config entry with validation metadata from Migration 011.
 * Extends the original ConfigEntry with default_value, value_type,
 * min/max constraints, allowed values, and permission tier.
 */
export interface EnhancedConfigEntry {
  readonly key: string;
  readonly value: unknown;
  readonly description: string | null;
  readonly category: string;
  readonly updatedAt: string;
  /** Intended default value from seed migration */
  readonly defaultValue: unknown;
  /** Value type — drives validation and UI widget */
  readonly valueType: ConfigValueType;
  /** Minimum allowed value (for number type) */
  readonly minValue: number | null;
  /** Maximum allowed value (for number type) */
  readonly maxValue: number | null;
  /** Allowed values (for string_enum type) */
  readonly allowedValues: readonly string[] | null;
  /** Permission tier: standard (admin) or safety (super_admin) */
  readonly permissionTier: PermissionTier;
}

// ---------------------------------------------------------------------------
// Config validation
// ---------------------------------------------------------------------------

/** Result of validating a proposed config value */
export interface ConfigValidationResult {
  readonly valid: boolean;
  readonly errors: readonly string[];
}

// ---------------------------------------------------------------------------
// Config change request — what the agent produces before confirmation
// ---------------------------------------------------------------------------

/**
 * A proposed config change. Created by the config agent's update tool
 * before the human confirms. Contains all information needed for the
 * reconfirmation flow (P10).
 */
export interface ConfigChangeRequest {
  /** Config key being changed */
  readonly key: string;
  /** Current value (for display and rollback) */
  readonly currentValue: unknown;
  /** Proposed new value */
  readonly proposedValue: unknown;
  /** Why the change matters — generated by the agent */
  readonly impact: string;
  /** Who is affected — generated by the agent */
  readonly affectedUsers: string;
  /** Whether this is reversible */
  readonly reversible: boolean;
  /** Permission tier of this config entry */
  readonly permissionTier: PermissionTier;
  /** Whether two-person approval is required for this change */
  readonly requiresApproval: boolean;
  /** Mandatory change comment from the admin */
  readonly changeComment: string;
}

// ---------------------------------------------------------------------------
// Config history — maps to platform_config_history table
// ---------------------------------------------------------------------------

/**
 * Source of a config change. Tracks how the change was made.
 */
export type ConfigChangeSource =
  | "admin_ui"
  | "config_agent"
  | "api"
  | "migration"
  | "system";

/**
 * A single config change history record.
 * Maps 1:1 to the platform_config_history table.
 */
export interface ConfigHistoryRecord {
  readonly id: string;
  readonly configKey: string;
  readonly previousValue: unknown;
  readonly newValue: unknown;
  readonly changedBy: string | null;
  readonly changeComment: string;
  readonly changeSource: ConfigChangeSource;
  readonly createdAt: string;
}

/** Options for querying config history */
export interface ConfigHistoryOptions {
  readonly configKey?: string;
  readonly changedBy?: string;
  readonly since?: string;
  readonly before?: string;
  readonly limit?: number;
}

// ---------------------------------------------------------------------------
// Two-person approval — maps to config_pending_approvals table
// ---------------------------------------------------------------------------

/** Status of a pending approval request */
export type ConfigApprovalStatus = "pending" | "approved" | "rejected" | "expired";

/**
 * A pending approval record.
 * Maps 1:1 to the config_pending_approvals table.
 */
export interface ConfigApprovalRecord {
  readonly id: string;
  readonly configKey: string;
  readonly currentValue: unknown;
  readonly proposedValue: unknown;
  readonly requestedBy: string | null;
  readonly changeComment: string;
  readonly impactSummary: string | null;
  readonly status: ConfigApprovalStatus;
  readonly reviewedBy: string | null;
  readonly reviewComment: string | null;
  readonly reviewedAt: string | null;
  readonly expiresAt: string;
  readonly createdAt: string;
}

/** Options for querying pending approvals */
export interface ConfigApprovalQueryOptions {
  readonly status?: ConfigApprovalStatus;
  readonly configKey?: string;
  readonly requestedBy?: string;
  readonly limit?: number;
}

// ---------------------------------------------------------------------------
// Impact correlation — joins config history with moderation audit
// ---------------------------------------------------------------------------

/**
 * Impact report for a config change. Shows what happened to moderation
 * outcomes after the change was made.
 *
 * Example: "After you changed moderation.level2.block_severity from
 * 'medium' to 'high', the block rate for Level 2 users dropped from
 * 12% to 4%."
 */
export interface ConfigImpactReport {
  /** The config change that was analyzed */
  readonly change: ConfigHistoryRecord;
  /** Period analyzed: from change time to now (or next change) */
  readonly periodStart: string;
  readonly periodEnd: string;
  /** Moderation stats before the change */
  readonly before: ConfigImpactMetrics;
  /** Moderation stats after the change */
  readonly after: ConfigImpactMetrics;
  /** Human-readable summary */
  readonly summary: string;
}

/** Moderation metrics for impact comparison */
export interface ConfigImpactMetrics {
  readonly totalScreenings: number;
  readonly blockCount: number;
  readonly warnCount: number;
  readonly allowCount: number;
  readonly escalateCount: number;
  readonly blockRate: number;
  readonly warnRate: number;
}

// ---------------------------------------------------------------------------
// Config search options
// ---------------------------------------------------------------------------

/** Options for searching config entries */
export interface ConfigSearchOptions {
  /** Search term — matches key, description, or category */
  readonly query?: string;
  /** Filter by category */
  readonly category?: string;
  /** Filter by permission tier */
  readonly permissionTier?: PermissionTier;
  /** Filter by value type */
  readonly valueType?: ConfigValueType;
}

// ---------------------------------------------------------------------------
// Config agent result — what the agent returns per conversation turn
// ---------------------------------------------------------------------------

/**
 * Tool call result from a single config agent tool invocation.
 * The config agent may invoke multiple tools per conversation turn;
 * each produces one of these results.
 */
export interface ConfigToolResult {
  /** Which tool was called */
  readonly toolId: string;
  /** Whether the tool call succeeded */
  readonly success: boolean;
  /** Tool output data */
  readonly data: unknown;
  /** Error message if failed */
  readonly error?: string;
  /** Duration of this tool call in ms */
  readonly durationMs: number;
}

/**
 * Full result from a config agent conversation turn.
 * Contains the agent's response, any tool calls made, and the
 * trajectory for observability.
 */
export interface ConfigAgentResult {
  /** Agent's natural language response to the admin */
  readonly response: string;
  /** Tool calls made during this turn */
  readonly toolResults: readonly ConfigToolResult[];
  /** Whether a config change is pending confirmation */
  readonly pendingChange: ConfigChangeRequest | null;
  /** Full trajectory for this turn (P18) */
  readonly trajectoryId: string;
  readonly agentId: string;
  readonly steps: readonly Step[];
  /** Total cost of this turn in USD */
  readonly totalCost: number;
  /** Total latency of this turn in ms */
  readonly totalLatencyMs: number;
}

// ---------------------------------------------------------------------------
// Config agent tool definitions (P5)
// ---------------------------------------------------------------------------

/**
 * Tool IDs for the config management agent.
 * Used as constants throughout the config agent module.
 */
export const CONFIG_TOOL_IDS = {
  SEARCH_CONFIG: "search_config",
  GET_CONFIG: "get_config",
  UPDATE_CONFIG: "update_config",
  GET_HISTORY: "get_history",
  COMPARE_TO_DEFAULTS: "compare_to_defaults",
  IMPACT_REPORT: "impact_report",
  BULK_REVIEW: "bulk_review",
  REQUEST_APPROVAL: "request_approval",
  APPROVE_CHANGE: "approve_change",
  REJECT_CHANGE: "reject_change",
} as const;

export type ConfigToolId = (typeof CONFIG_TOOL_IDS)[keyof typeof CONFIG_TOOL_IDS];

// ---------------------------------------------------------------------------
// Gotchas (L17) — module-level scar tissue
// ---------------------------------------------------------------------------
//
// 1. EnhancedConfigEntry.value and defaultValue are `unknown` — the DB
//    stores JSONB. Always validate with valueType before casting.
//    A "number" config stores its value as a JSON number, but Supabase
//    may return it as a string. Parse based on valueType.
//
// 2. ConfigApprovalRecord.requestedBy and reviewedBy are UUID strings,
//    not user objects. Join with users table if display name is needed.
//
// 3. PermissionTier is "standard" | "safety" — the DB column is TEXT,
//    not an enum. Validate at the boundary (API route or service layer).
//
// 4. ConfigHistoryRecord.previousValue can be null for the first change
//    to a key (no previous value existed).
//
// 5. ConfigChangeSource must match the DB default 'admin_ui'. The config
//    agent should always set change_source = 'config_agent'.
//
// 6. minValue/maxValue are stored as JSONB in the DB (not native numbers).
//    Migration 011 uses string literals like '1', '0.0'. Parse to number
//    at the service boundary.
//
// 7. allowedValues is a JSONB column storing a JSON array of strings.
//    Parse with JSON.parse if it arrives as a string from Supabase.
