/**
 * lib/supabase/types.ts — Database type definitions
 *
 * This file defines the TypeScript types for the Supabase database schema.
 * In production, this would be auto-generated by `supabase gen types typescript`.
 *
 * For now, this is a placeholder that will be populated when we create
 * the database schema in Sprint 1 Task 1.3.
 *
 * Usage:
 *   import type { Database } from "@/lib/supabase/types";
 */

export interface Database {
  public: {
    // eslint-disable-next-line @typescript-eslint/no-empty-object-type
    Tables: {
      // Populated in Task 1.3 — Database Schema
      // players: { Row: {...}, Insert: {...}, Update: {...} }
      // roles: { Row: {...}, Insert: {...}, Update: {...} }
      // permissions: { Row: {...}, Insert: {...}, Update: {...} }
      // ... etc.
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
